# Generated by Django 5.2.6 on 2025-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_password', models.CharField(max_length=5)),
                ('is_bool', models.BooleanField(default=False)),
                ('code_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
