# Generated by Django 5.2.6 on 2025-10-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
