# Generated by Django 5.2.6 on 2025-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_students_created_at_students_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkget',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
