# Generated by Django 5.2.6 on 2025-10-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_homeworkget_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
